### ISSUE TITLE
`pip download frozenlist` is building and installing a lot of stuff

### ISSUE THREAD

**Issue by markmc** [markmc/rebuilding-the-wheel#12]
Just noticed a long pause in `build-wheels.sh` at:

```
pip download --no-deps --no-binary :all: 'frozenlist>=1.1.0'
```

it's spending a lot of time in 'installing build backend dependencies'

This is definitely not what we want, and we already have the sdists downloaded locally anyway

**Comment by dhellmann** [comment]
I'm looking at this. I think this is the same issue as #11 right?

**Comment by dhellmann** [comment]
https://github.com/pypa/pip/issues/8387 is relevant.

For some reason when pip downloads the package it wants to verify some metadata, and they decided that only reliable way to do that is to build the wheel and then examine it.

**Comment by dhellmann** [comment]
And that leads to https://github.com/pypa/pip/issues/1884 which remains open since 2014, with a couple of pleas for someone to contribute the fix. So, we could look at doing that, eventually. I had limited success contributing a patch to pip at one point for OpenStack, but that may have been a timing issue so I'd say it's worth trying again for this issue as part of a good long term solution. I'll see if I can come up with a short-term hack in the mean time.

**Comment by dhellmann** [comment]
https://github.com/dhellmann/rebuilding-the-wheel/tree/simple-downloader has a start of a simple download script. It doesn't handle "extras" yet.

**Comment by dhellmann** [comment]
> https://github.com/dhellmann/rebuilding-the-wheel/tree/simple-downloader has a start of a simple download script. It doesn't handle "extras" yet.

Allowing "extras" brings in some packages that are causing additional issues. One requires a newer version of Python, for example:

```
+ ./mirror-sdists.sh:48 	python3 ./resolve_and_download.py --dest sdists-repo/downloads/ 'entangled-cli[rich]; extra == "docs"'
Resolving entangled-cli[rich]; extra == "docs"
get project entangled-cli
Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 397, in resolve
skipping entangled_cli-2.0.0a1-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0a1.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0a2-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0a2.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0a3-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0a3.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b1-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b1.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b2-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b2.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b4-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b4.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b5-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b5.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b6-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0b6.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.0.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.1-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.1.tar.gz because of python version >=3.11,<4.0
skipping entangled_cli-2.0.2-py3-none-any.whl because of python version >=3.11,<4.0
skipping entangled_cli-2.0.2.tar.gz because of python version >=3.11,<4.0
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: <Requirement('entangled-cli[rich]; extra == "docs"')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/./resolve_and_download.py", line 218, in <module>
    main()
  File "/home/dhellmann/devel/rebuilding-the-wheel/./resolve_and_download.py", line 212, in main
    result = resolver.resolve(requirements)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<Requirement('entangled-cli[rich]; extra == "docs"')>, parent=None)]
```

**Comment by dhellmann** [comment]
> > https://github.com/dhellmann/rebuilding-the-wheel/tree/simple-downloader has a start of a simple download script. It doesn't handle "extras" yet.
> 
> Allowing "extras" brings in some packages that are causing additional issues. One requires a newer version of Python, for example:

I've updated the branch to ignore unresolvable dependencies for now. That should let the mirror script run further, and we'll only see build errors if the package is a build dependency. We might not be able to install the packages we build without the missing dependency, of course.
