### ISSUE TITLE
issue building meson

### ISSUE THREAD

**Issue by dhellmann** [markmc/rebuilding-the-wheel#21]
the main branch at c5cf85d gives

```
+ ./mirror-sdists.sh:149 	tee /home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/requirements.txt
Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
    whl_basename = backend.build_wheel(metadata_directory, config_settings)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/meson_python-0.15.0/mesonpy/__init__.py", line 985, in wrapper
    return func(*args, **kwargs)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/meson_python-0.15.0/mesonpy/__init__.py", line 1038, in build_wheel
    with _project(config_settings) as project:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/meson_python-0.15.0/mesonpy/__init__.py", line 912, in _project
    yield Project(source_dir, build_dir, meson_args, editable_verbose)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/meson_python-0.15.0/mesonpy/__init__.py", line 635, in __init__
    self._meson = _get_meson_command(pyproject_config.get('meson'))
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/meson_python-0.15.0/meson_python-0.15.0/mesonpy/__init__.py", line 947, in _get_meson_command
    meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
  File "/usr/lib64/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'meson'

Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/extract-requires.py", line 93, in <module>
    metadata_path = hook_caller.prepare_metadata_for_build_wheel("./")
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/dhellmann/devel/rebuilding-the-wheel/extract-requires.py", line 40, in logging_subprocess_runner
    raise subprocess.CalledProcessError(completed.returncode, cmd, output)
subprocess.CalledProcessError: Command '['/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/bin/python3.9', '/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py', 'prepare_metadata_for_build_wheel', '/tmp/tmppn8yeewk']' returned non-zero exit status 1.
```

**Comment by markmc** [comment]
Yeah, just looking at this

On a Python 3.9 system, in `meson_python-0.15.0`:

```
$ python3 ../../../extract-requires.py --build-system 'meson-python>=0.15.0,<0.16.0'
meson >= 1.2.3; python_version >= "3.12"
tomli >= 1.0.0; python_version < "3.11"
pyproject-metadata >= 0.7.1
meson >= 0.63.3; python_version < "3.12"
```

i.e. meson_python requires a different meson version to build, depending on the python version you're building with. Or more precisely, `meson>=0.63.3,<1.2.3`	will work on older python versions but won't work on 3.12.

Currently, we ignore this and go on to build meson-1.4.0:

```
python3 ./resolve_and_download.py ... 'meson >= 1.2.3; python_version >= "3.12"'
Saved .../sdists-repo/downloads/meson-1.4.0.tar.gz
...
Successfully built meson-1.4.0-py3-none-any.whl
```

and then later we try to install it, but still using the `>= 3.12` marker:

```
$ pip -vvv install --upgrade --disable-pip-version-check --only-binary :all: --index-url http://localhost:9090/simple 'meson >= 1.2.3; python_version >= "3.12"'
...
Ignoring meson: markers 'python_version >= "3.12"' don't match your environment
```

And we never attempt to install it with the `< "3.12"` marker because we assume we have already processed this because the sdist was downloaded already.

Note, if the order of the requires is reversed - i.e. if we hit `meson >= 0.63.3; python_version < "3.12"` first, then we still build 1.4.0 but this time it installs fine	because	we have	the `< "3.12"` marker in the `pip install` command.

I'm working on a fix to properly evaluate against python_version, etc.
