### ISSUE TITLE
build-wheels.sh failing at SQLAlchemy

### ISSUE THREAD

**Issue by markmc** [markmc/rebuilding-the-wheel#3]
`build-wheels.sh` failing at:

```
+ pip -vvv --disable-pip-version-check wheel --index-url http://localhost:8000/simple ./SQLAlchemy-2.0.28.tar.gz
...
Will try a different candidate, due to conflict:
    sqlalchemy 2.0.28 depends on typing-extensions>=4.6.0
ERROR: Could not find a version that satisfies the requirement typing-extensions>=4.6.0 (from sqlalchemy) (from versions: none)
ERROR: No matching distribution found for typing-extensions>=4.6.0
```

with [this build-order.json](https://gist.github.com/markmc/aed2781a437e0aa8060a5ea617d36848). Clearly we're not collecting the `typing-extensions` dependency somehow. This is likely an error with calling `prepare_metadata_for_build_wheel()` for `SQLAlchemy-2.0.28`.

**Comment by dhellmann** [comment]
I get

```
Exception information:
Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))'), parent=LinkCandidate('file:///home/dhellmann/devel/rebuilding-the-wheel/wheelbuildnScp/SQLAlchemy-2.0.28.tar.gz'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_internal/commands/wheel.py", line 147, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/home/dhellmann/devel/rebuilding-the-wheel/venvSF6Z/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))
```

**Comment by dhellmann** [comment]
I'm looking at this in https://github.com/dhellmann/rebuilding-the-wheel/tree/fix-sqlalchemy

I think we need to not be ignoring dependencies with markers.
