### ISSUE TITLE
mirror-sdists.sh failing at requests

### ISSUE THREAD

**Issue by markmc** [markmc/rebuilding-the-wheel#4]
```
Processing ./sdists-repo/downloads/requests-2.31.0.tar.gz with pyproject.toml:
+ ./mirror-sdists.sh:72         cat ./tmpUFt2/tmpZu1w/requests-2.31.0/pyproject.toml
[tool.isort]
profile = "black"
src_paths = ["requests", "test"]
honor_noqa = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
minversion = "6.2"
testpaths = [
    "requests",
    "tests",
]
+ ./mirror-sdists.sh:74         read -r req_iter
++ ./mirror-sdists.sh:74        dirname ./tmpUFt2/tmpZu1w/requests-2.31.0/pyproject.toml
+ ./mirror-sdists.sh:74         cd ./tmpUFt2/tmpZu1w/requests-2.31.0
+ ./mirror-sdists.sh:74         python3 /home/markmc/ai-ml/distro/rebuilding-the-wheel/extract-requires.py --build-system
+ ./mirror-sdists.sh:88         read -r req_iter
++ ./mirror-sdists.sh:88        dirname ./tmpUFt2/tmpZu1w/requests-2.31.0/pyproject.toml
+ ./mirror-sdists.sh:88         cd ./tmpUFt2/tmpZu1w/requests-2.31.0
+ ./mirror-sdists.sh:88         python3 /home/markmc/ai-ml/distro/rebuilding-the-wheel/extract-requires.py --build-backend
+ ./mirror-sdists.sh:104        read -r req_iter
++ ./mirror-sdists.sh:104       dirname ./tmpUFt2/tmpZu1w/requests-2.31.0/pyproject.toml
+ ./mirror-sdists.sh:104        cd ./tmpUFt2/tmpZu1w/requests-2.31.0
+ ./mirror-sdists.sh:104        python3 /home/markmc/ai-ml/distro/rebuilding-the-wheel/extract-requires.py
Traceback (most recent call last):
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 142, in prepare_metadata_for_build_wheel
    backend = _build_backend()
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name

Traceback (most recent call last):
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/extract-requires.py", line 59, in <module>
    metadata_path = hook_caller.prepare_metadata_for_build_wheel("./")
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/markmc/ai-ml/distro/rebuilding-the-wheel/extract-requires.py", line 39, in logging_subprocess_runner
    raise subprocess.CalledProcessError(completed.returncode, cmd, output)
subprocess.CalledProcessError: Command '['/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/bin/python3', '/home/markmc/ai-ml/distro/rebuilding-the-wheel/tmpUFt2/venv/lib64/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py', 'prepare_metadata_for_build_wheel', '/tmp/tmpmehci58s']' returned non-zero exit status 1.
```

**Comment by markmc** [comment]
From @dhellmann 

> One unsolved issue that now comes up with that version of the script is that not all modern packages have all of the metadata in the toml file. The requests package in particular still uses a setup.py.
> I think you can rely on package-build-time dependencies being expressed in the toml file, but I'm not sure of that. The requests package doesn't seem to have any build dependencies. If that assumption holds, then I think the right thing to do is change the part of mirror-sdists.sh that looks at the "regular" dependencies so that it first builds a wheel, then parses the METADATA from that package. That would isolate you from all of the weirdness that's possible with setup.py file, as well as any other tools that use a different input file.
> The library pip uses is released separately, and might be useful directly. https://github.com/sarugaku/resolvelib/blob/main/examples/pypi_wheel_provider.py
>https://pip-tools.readthedocs.io/en/latest/ might also be useful
