### ISSUE TITLE
maturin wheel build fails

### ISSUE THREAD

**Issue by dhellmann** [markmc/rebuilding-the-wheel#56]
The rust toolchain is trying to install something to build the wheel.

```
Processing /home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1
  Added file:///home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1 to build tracker '/tmp/pip-build-tracker-w7teke3v'
  Created temporary directory: /tmp/pip-build-env-8lwmpcn8
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  WARNING: The directory '/home/dhellmann/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
  Using pip 24.0 from /home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/lib/python3.9/site-packages/pip (python 3.9)
  Looking in indexes: http://127.0.0.1:8000/simple/
  Collecting setuptools
    Downloading http://127.0.0.1:8000/simple/setuptools/setuptools-69.2.0-py3-none-any.whl (821 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.5/821.5 kB 702.8 MB/s eta 0:00:00
  Collecting wheel>=0.36.2
    Downloading http://127.0.0.1:8000/simple/wheel/wheel-0.43.0-py3-none-any.whl (65 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 500.5 MB/s eta 0:00:00
  Collecting tomli>=1.1.0
    Downloading http://127.0.0.1:8000/simple/tomli/tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting setuptools-rust>=1.4.0
    Downloading http://127.0.0.1:8000/simple/setuptools-rust/setuptools_rust-1.9.0-py3-none-any.whl (26 kB)
  Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=1.4.0)
    Downloading http://127.0.0.1:8000/simple/semantic-version/semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
  Installing collected packages: wheel, tomli, setuptools, semantic-version, setuptools-rust
    Creating /tmp/pip-build-env-8lwmpcn8/overlay/bin
    changing mode of /tmp/pip-build-env-8lwmpcn8/overlay/bin/wheel to 755
  Successfully installed semantic-version-2.10.0 setuptools-69.2.0 setuptools-rust-1.9.0 tomli-2.0.1 wheel-0.43.0
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Getting requirements to build wheel: finished with status 'done'
  Created temporary directory: /tmp/pip-modern-metadata-igcdcu4h
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  /tmp/pip-build-env-8lwmpcn8/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:83: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
    corresp(dist, value, root_dir)
  running dist_info
  creating /tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info
  writing /tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.json' under directory 'src/python_interpreter'
  writing manifest file '/tmp/pip-modern-metadata-igcdcu4h/maturin.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-igcdcu4h/maturin-1.5.1.dist-info'
  Preparing metadata (pyproject.toml): finished with status 'done'
  Source in /home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1 has version 1.5.1, which satisfies requirement maturin==1.5.1 from file:///home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1
  Removed maturin==1.5.1 from file:///home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1 from build tracker '/tmp/pip-build-tracker-w7teke3v'
Created temporary directory: /tmp/pip-unpack-mrjxs65t
Created temporary directory: /tmp/pip-unpack-ruf1vl35
Building wheels for collected packages: maturin
  Created temporary directory: /tmp/pip-wheel-by4aig8d
  Destination directory: /tmp/pip-wheel-by4aig8d
  Building wheel for maturin (pyproject.toml): started
  Running command Building wheel for maturin (pyproject.toml)
  /tmp/pip-build-env-8lwmpcn8/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:83: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
    corresp(dist, value, root_dir)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-cpython-39
  creating build/lib.linux-aarch64-cpython-39/maturin
  copying maturin/__init__.py -> build/lib.linux-aarch64-cpython-39/maturin
  copying maturin/__main__.py -> build/lib.linux-aarch64-cpython-39/maturin
  copying maturin/import_hook.py -> build/lib.linux-aarch64-cpython-39/maturin
  running egg_info
  creating maturin.egg-info
  writing maturin.egg-info/PKG-INFO
  writing dependency_links to maturin.egg-info/dependency_links.txt
  writing requirements to maturin.egg-info/requires.txt
  writing top-level names to maturin.egg-info/top_level.txt
  writing manifest file 'maturin.egg-info/SOURCES.txt'
  reading manifest file 'maturin.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.json' under directory 'src/python_interpreter'
  writing manifest file 'maturin.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
      Updating crates.io index
  warning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 272 ms: Couldn't connect to server)
  warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)
  warning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)
  error: failed to get `anyhow` as a dependency of package `maturin v1.5.1 (/home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1)`

  Caused by:
    failed to query replaced source registry `crates-io`

  Caused by:
    download of config.json failed

  Caused by:
    failed to download from `https://index.crates.io/config.json`

  Caused by:
    [7] Couldn't connect to server (Failed to connect to index.crates.io port 443 after 0 ms: Couldn't connect to server)
  error: `cargo metadata --manifest-path Cargo.toml --format-version 1 --locked` failed with code 101
  -- Output captured from stdout:

  error: subprocess-exited-with-error

  × Building wheel for maturin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/bin/python3.9 /home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpp4dtosk2
  cwd: /home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1/maturin-1.5.1
  Building wheel for maturin (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for maturin
Failed to build maturin
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/lib64/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/lib64/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/dhellmann/devel/rebuilding-the-wheel/work-dir/venv-python3.9/lib64/python3.9/site-packages/pip/_internal/commands/wheel.py", line 181, in run
    raise CommandError("Failed to build one or more wheels")
pip._internal.exceptions.CommandError: Failed to build one or more wheels
Removed build tracker: '/tmp/pip-build-tracker-w7teke3v'

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/__main__.py", line 46, in <module>
    main()
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/__main__.py", line 42, in main
    sdist.handle_requirement(ctx, Requirement(toplevel))
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/sdist.py", line 55, in handle_requirement
    handle_requirement(ctx, dep, next_req_type, next_why)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/sdist.py", line 55, in handle_requirement
    handle_requirement(ctx, dep, next_req_type, next_why)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/sdist.py", line 27, in handle_requirement
    resolved = handle_requirement(ctx, dep, next_req_type, next_why)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/sdist.py", line 46, in handle_requirement
    wheels.build_wheel(ctx, req_type, req, resolved_name, why, sdist_root_dir)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/wheels.py", line 13, in build_wheel
    wheel_filenames = builder(ctx, req_type, req, resolved_name, why, sdist_root_dir)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/wheels.py", line 35, in _default_build_wheel
    external_commands.run(cmd, cwd=sdist_root_dir)
  File "/home/dhellmann/devel/rebuilding-the-wheel/mirror_builder/external_commands.py", line 28, in run
    raise subprocess.CalledProcessError(completed.returncode, cmd, output)
subprocess.CalledProcessError: Command '['firejail', '--net=none', '--join=local-wheel-server', 'pip', '-vvv', '--disable-pip-version-check', 'wheel', '--no-cache-dir', '--index-url', 'http://127.0.0.1:8000/simple/', '--only-binary', ':all:', '--wheel-dir', PosixPath('/home/dhellmann/devel/rebuilding-the-wheel/work-dir/maturin-1.5.1'), '--no-deps', '.']' returned non-zero exit status 1.
```

_Originally posted by @dhellmann in https://github.com/markmc/rebuilding-the-wheel/issues/54#issuecomment-2040548366_

**Comment by dhellmann** [comment]
Maturin can build in CI. It looks like firejail isn't working to block network access there.

```
2024-04-05T20:26:49.8434661Z DEBUG:mirror_builder.external_commands:17: running: firejail --net=none /src/work-dir/maturin-1.5.1/build-3.9.18/bin/python3 -m pip -vvv --disable-pip-version-check wheel --no-cache-dir --no-build-isolation --only-binary :all: --wheel-dir /src/work-dir/maturin-1.5.1 --no-deps .
2024-04-05T20:29:39.2251551Z DEBUG:mirror_builder.external_commands:29: output: Warning: an existing sandbox was detected. /src/work-dir/maturin-1.5.1/build-3.9.18/bin/python3 will run without any additional sandboxing features
2024-04-05T20:29:39.2253697Z Created temporary directory: /tmp/pip-build-tracker-bt5de3ny
2024-04-05T20:29:39.2254754Z Initialized build tracking at /tmp/pip-build-tracker-bt5de3ny
2024-04-05T20:29:39.2255695Z Created build tracker: /tmp/pip-build-tracker-bt5de3ny
2024-04-05T20:29:39.2257229Z Entered build tracker: /tmp/pip-build-tracker-bt5de3ny
2024-04-05T20:29:39.2257867Z Created temporary directory: /tmp/pip-wheel-j2vi446l
2024-04-05T20:29:39.2258492Z Created temporary directory: /tmp/pip-ephem-wheel-cache-0vvdtbih
2024-04-05T20:29:39.2259223Z Processing /src/work-dir/maturin-1.5.1/maturin-1.5.1
2024-04-05T20:29:39.2260153Z   Added file:///src/work-dir/maturin-1.5.1/maturin-1.5.1 to build tracker '/tmp/pip-build-tracker-bt5de3ny'
2024-04-05T20:29:39.2261301Z   Created temporary directory: /tmp/pip-modern-metadata-1mokeu9t
2024-04-05T20:29:39.2261798Z   Preparing metadata (pyproject.toml): started
2024-04-05T20:29:39.2262286Z   Running command Preparing metadata (pyproject.toml)
2024-04-05T20:29:39.2262856Z   running dist_info
2024-04-05T20:29:39.2263320Z   creating /tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info
2024-04-05T20:29:39.2264263Z   writing /tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/PKG-INFO
2024-04-05T20:29:39.2265210Z   writing dependency_links to /tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/dependency_links.txt
2024-04-05T20:29:39.2266522Z   writing requirements to /tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/requires.txt
2024-04-05T20:29:39.2267669Z   writing top-level names to /tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/top_level.txt
2024-04-05T20:29:39.2268672Z   writing manifest file '/tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2269729Z   reading manifest file '/tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2270451Z   reading manifest template 'MANIFEST.in'
2024-04-05T20:29:39.2271160Z   warning: no files found matching '*.json' under directory 'src/python_interpreter'
2024-04-05T20:29:39.2272092Z   writing manifest file '/tmp/pip-modern-metadata-1mokeu9t/maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2272872Z   creating '/tmp/pip-modern-metadata-1mokeu9t/maturin-1.5.1.dist-info'
2024-04-05T20:29:39.2273584Z   Preparing metadata (pyproject.toml): finished with status 'done'
2024-04-05T20:29:39.2275070Z   Source in /src/work-dir/maturin-1.5.1/maturin-1.5.1 has version 1.5.1, which satisfies requirement maturin==1.5.1 from file:///src/work-dir/maturin-1.5.1/maturin-1.5.1
2024-04-05T20:29:39.2276595Z   Removed maturin==1.5.1 from file:///src/work-dir/maturin-1.5.1/maturin-1.5.1 from build tracker '/tmp/pip-build-tracker-bt5de3ny'
2024-04-05T20:29:39.2277532Z Created temporary directory: /tmp/pip-unpack-yfkshmgx
2024-04-05T20:29:39.2278148Z Created temporary directory: /tmp/pip-unpack-mw81tmjt
2024-04-05T20:29:39.2278618Z Building wheels for collected packages: maturin
2024-04-05T20:29:39.2279156Z   Created temporary directory: /tmp/pip-wheel-lm3iw9tr
2024-04-05T20:29:39.2279917Z   Destination directory: /tmp/pip-wheel-lm3iw9tr
2024-04-05T20:29:39.2280451Z   Building wheel for maturin (pyproject.toml): started
2024-04-05T20:29:39.2280990Z   Running command Building wheel for maturin (pyproject.toml)
2024-04-05T20:29:39.2281461Z   running bdist_wheel
2024-04-05T20:29:39.2281798Z   running build
2024-04-05T20:29:39.2282025Z   running build_py
2024-04-05T20:29:39.2282252Z   creating build
2024-04-05T20:29:39.2282674Z   creating build/lib.linux-x86_64-cpython-39
2024-04-05T20:29:39.2283205Z   creating build/lib.linux-x86_64-cpython-39/maturin
2024-04-05T20:29:39.2283811Z   copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-39/maturin
2024-04-05T20:29:39.2284642Z   copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-39/maturin
2024-04-05T20:29:39.2285340Z   copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-39/maturin
2024-04-05T20:29:39.2285831Z   running egg_info
2024-04-05T20:29:39.2286155Z   creating maturin.egg-info
2024-04-05T20:29:39.2286516Z   writing maturin.egg-info/PKG-INFO
2024-04-05T20:29:39.2287088Z   writing dependency_links to maturin.egg-info/dependency_links.txt
2024-04-05T20:29:39.2287742Z   writing requirements to maturin.egg-info/requires.txt
2024-04-05T20:29:39.2288361Z   writing top-level names to maturin.egg-info/top_level.txt
2024-04-05T20:29:39.2288987Z   writing manifest file 'maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2289556Z   reading manifest file 'maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2290016Z   reading manifest template 'MANIFEST.in'
2024-04-05T20:29:39.2290692Z   warning: no files found matching '*.json' under directory 'src/python_interpreter'
2024-04-05T20:29:39.2291408Z   writing manifest file 'maturin.egg-info/SOURCES.txt'
2024-04-05T20:29:39.2291976Z   running build_ext
2024-04-05T20:29:39.2292214Z   running build_rust
2024-04-05T20:29:39.2292554Z       Updating crates.io index
2024-04-05T20:29:39.2292844Z    Downloading crates ...
2024-04-05T20:29:39.2293232Z     Downloaded time-core v0.1.2
2024-04-05T20:29:39.2293564Z     Downloaded bitflags v1.3.2
2024-04-05T20:29:39.2293861Z     Downloaded cab v0.4.1
2024-04-05T20:29:39.2294217Z     Downloaded camino v1.1.6
2024-04-05T20:29:39.2294502Z     Downloaded tinyvec_macros v0.1.1
2024-04-05T20:29:39.2294915Z     Downloaded base64 v0.13.1
2024-04-05T20:29:39.2295248Z     Downloaded twox-hash v1.6.3
2024-04-05T20:29:39.2295636Z     Downloaded unicase v2.7.0
2024-04-05T20:29:39.2295986Z     Downloaded wild v2.2.1
...
```

**Comment by dhellmann** [comment]
Related to #80
